Release 1.2
hyperlinkgroup/swift-firebase-manager pull request #3
Opened 2023-02-17 12:30 UTC by annanna

- Added Email Authentication
- Added CollectionRepository 
- Improved Error Response
- Added Provider-Functionalities
- Added the option to merge objects when updating (default is false)
- Improved Authorization Checking

2023-02-20 06:40 UTC, kaevinio requested changes

2023-02-20 06:40 UTC, kaevinio commented on .github/README.md
> +By default the `AuthenticationManager` allows three authentication methods: Sign in with Email and Password, by using the Apple ID and anonymous login. If you want to restrict the providers, you can
Ich glaube, dass nach default ein Komma kommt

2023-02-20 06:40 UTC, kaevinio commented on .github/README.md
> +By default the `AuthenticationManager` allows three authentication methods: Sign in with Email and Password, by using the Apple ID and anonymous login. If you want to restrict the providers, you can
Und hinter nach with that auch

2023-02-20 06:40 UTC, kaevinio commented on .github/README.md
>  The Authentication Manager controls the whole authentication flow and returns you the handled error without any further work.
returns you?

2023-02-20 06:40 UTC, kaevinio commented on Sources/AuthenticationManager/Authentication/Sign In/EmailPassword/EmailPassword.swift
> +            } else {
Sonst schreiben wir ein if let error und dann return aber hier ein else?

2023-02-20 06:40 UTC, kaevinio commented on Sources/AuthenticationManager/Authentication/Sign In/EmailPassword/EmailPassword.swift
> +                if let error = error {
if let error

2023-02-20 06:40 UTC, kaevinio commented on Sources/AuthenticationManager/AuthenticationProvider.swift
> +        if hasUser {
wäre hier ein guard hasUser nicht besser, um das darin eine Ebene nach vorne zu schieben?

2023-02-20 06:40 UTC, kaevinio commented on Sources/AuthenticationManager/UserRepositoryProtocol.swift
> +
hier ist eine Leerzeile zu viel

2023-02-20 06:40 UTC, kaevinio commented on Sources/AuthenticationManager/UserRepositoryProtocol.swift
> +
Hier auch

2023-02-20 06:40 UTC, kaevinio commented on Sources/FirestoreManager/CollectionRepository.swift
> +    private func getPath(id: String) -> String {
die Funktion wird ja von create und update genutzt, fände es besser die von der gruppierung ans ende zu stellen, dass die CRUD-Funktionen zusammen sind und die als Helper am Schluss

2023-02-22 12:51 UTC, annanna commented on Sources/AuthenticationManager/AuthenticationProvider.swift
> +        if hasUser {
joa..also an sich geht's ja hier darum überhaupt den `currentProvider` zu setzen und hatte ich mich gegen `guard` entschieden, weil es ja trotzdem ein valider Fall und keine Ausnahme ist. Aber vielleicht ist es anders ein bisschen besser lesbar, ich ändere es mal

2023-02-23 07:21 UTC, kaevinio approved these changes

2023-02-23 09:20 UTC, merged